[package]
name = "universal2_rust"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies.pyo3]
# TODO: can use PyO3 0.14 once released
git = "https://github.com/PyO3/pyo3.git"
features = ["extension-module"]
