[package]
name = "universal2_rust"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies.pyo3]
git = "https://github.com/PyO3/pyo3.git"
# version = "0.13.2"
features = ["extension-module"]
