from pathlib import Path
import generated_files


def test_rust_extension():
    assert generated_files.library_ok()


def test_data_file_content():
    expected = {
        Path("my_file.txt"): "Generated by a build script.\n",
        Path("_data") / "dir" / "a.txt": "This is file A.\n",
        Path("_data") / "dir" / "b.txt": "This is file B.\n",
    }
    assert generated_files.data_files_content() == expected
